name: Mypy and PEP 8

on: [push]

jobs:
  mypy-pep8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy flake8
    - name: Mypy
      run: |
        # Replace src/ with the path to your Python source code
        mypy Python_homework1/ --ignore-missing-imports
    - name: Flake8
      run: |
        # Replace src/ with the path to your Python source code
        flake8 Python_homework1/